kfscftl-objs  := ./fscftl-init.o
kfscftl-objs  += ./core.o
kfscftl-objs  += ./namespace.o
kfscftl-objs  += ./hwcfg/regrw.o
kfscftl-objs  += ./datapath/ppa-ops.o
kfscftl-objs  += ./datapath/bio-wr.o
kfscftl-objs  += ./build_recovery/mcp.o
kfscftl-objs  += ./build_recovery/power-cycle.o
kfscftl-objs  += ./build_recovery/crash-recovery.o
kfscftl-objs  += ./bootblk/bootblk-mngr.o
kfscftl-objs  += ./writecache/wcb-mngr.o
kfscftl-objs  += ./systbl/sys-meta.o
kfscftl-objs  += ./backend/be-cdev.o

fscftl-y := ./fscftl-init.o
fscftl-y += ./core.o
fscftl-y += ./namespace.o
fscftl-y += ./datapath/ppa-ops.o
fscftl-y += ./datapath/bio-wr.o
fscftl-y += ./hwcfg/regrw.o
fscftl-y += ./build_recovery/mcp.o
fscftl-y += ./build_recovery/power-cycle.o
fscftl-y += ./build_recovery/crash-recovery.o
fscftl-y += ./bootblk/bootblk-mngr.o
fscftl-y += ./writecache/wcb-mngr.o
fscftl-y += ./systbl/sys-meta.o
fscftl-y += ./backend/be-cdev.o

ccflags-y += -g

obj-m := fscftl.o
