kfscftl-objs  := ./fscftl-init.o
kfscftl-objs  += ./namespace.o
kfscftl-objs  += ./hwcfg/regrw.o
kfscftl-objs  += ./build_recovery/mcp.o
kfscftl-objs  += ./build_recovery/power-cycle.o
kfscftl-objs  += ./build_recovery/crash-recovery.o

fscftl-y := ./fscftl-init.o
fscftl-y += ./namespace.o
fscftl-y += ./hwcfg/regrw.o
fscftl-y += ./build_recovery/mcp.o
fscftl-y += ./build_recovery/power-cycle.o
fscftl-y += ./build_recovery/crash-recovery.o

ccflags-y += -g

obj-m := fscftl.o
