/* THIS FILE IS GENERATED BY CONFIGURE SCRIPT AUTOMATICALLY */

#ifndef FLASH_CFG_H_
#define FLASH_CFG_H_

#include "cfg_2TB_MCL95B.h"
//#include "cfg_2TB_TH58TFG9DFK.h"

#endif /* FLASH_CFG_H_ */

